### ISSUE TITLE
"sample value too large"', src/api/lookahead.rs:154:47

### ISSUE THREAD

**Issue by rubdottocom** [xiph/rav1e#2849]
**Describe the bug**
`"sample value too large"', src/api/lookahead.rs:154:47'` error encoding a 4k hevc to AV1

**To Reproduce**
```
ffmpeg -i 20210213_121844.mp4
 -c:v librav1e -qp 80 -speed 4
 -tile-columns 2 -tile-rows 2
  -c:a libfdk_aac -b:a 128k
   20210213_121844_av1.mp4
```

**Expected behavior**
Encode the video

**Required Information**
```
cargo 1.56.0 (4ed5d137b 2021-10-04)
rustc 1.56.1 (59eed8a2a 2021-11-01)
NASM version 2.15.05 compiled on Nov  5 2021
```
Version:
```
rav1e 0.5.0-beta (0.5.0-beta) (release)
```
Operating system:
```
Linux  5.11.0-40-generic #44-Ubuntu SMP Wed Oct 20 16:16:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Console Output**
```
ffmpeg -i 20210213_121844.mp4
 -c:v librav1e -qp 80 -speed 4
 -tile-columns 2 -tile-rows 2
  -c:a libfdk_aac -b:a 128k
   20210213_121844_av1.mp4
ffmpeg version N-104465-g08a501946f Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.3.0-1ubuntu1)
  configuration: --prefix=/home/rub/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/home/rub/ffmpeg_build/include --extra-ldflags=-L/home/rub/ffmpeg_build/lib --extra-libs='-lpthread -lm' --ld=g++ --bindir=/home/rub/bin --enable-gpl --enable-gnutls --enable-libaom --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libsvtav1 --enable-libdav1d --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-librav1e --enable-nonfree
  libavutil      57.  7.100 / 57.  7.100
  libavcodec     59. 12.100 / 59. 12.100
  libavformat    59.  8.100 / 59.  8.100
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 16.101 /  8. 16.101
  libswscale      6.  1.100 /  6.  1.100
  libswresample   4.  0.100 /  4.  0.100
  libpostproc    56.  0.100 / 56.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '20210213_121844.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    creation_time   : 2021-02-13T11:20:22.000000Z
    com.android.version: 11
    com.android.capture.fps: 30.000000
  Duration: 00:01:37.12, start: 0.000000, bitrate: 53890 kb/s
  Stream #0:0[0x1](eng): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x2160, 53632 kb/s, SAR 1:1 DAR 16:9, 29.95 fps, 30 tbr, 90k tbn (default)
    Metadata:
      creation_time   : 2021-02-13T11:20:22.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
    Side data:
      displaymatrix: rotation of -90.00 degrees
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 256 kb/s (default)
    Metadata:
      creation_time   : 2021-02-13T11:20:22.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
File '20210213_121844_av1.mp4' already exists. Overwrite? [y/N] y
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (native) -> av1 (librav1e))
  Stream #0:1 -> #0:1 (aac (native) -> aac (libfdk_aac))
Press [q] to stop, [?] for help
Output #0, mp4, to '20210213_121844_av1.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: isommp42
    com.android.capture.fps: 30.000000
    com.android.version: 11
    encoder         : Lavf59.8.100
  Stream #0:0(eng): Video: av1 (av01 / 0x31307661), yuv420p10le(tv, bt2020nc/bt2020/smpte2084, progressive), 2160x3840 [SAR 1:1 DAR 9:16], q=2-31, 30 fps, 15360 tbn (default)
    Metadata:
      creation_time   : 2021-02-13T11:20:22.000000Z
      handler_name    : VideoHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.12.100 librav1e
    Side data:
      displaymatrix: rotation of -0.00 degrees
  Stream #0:1(eng): Audio: aac (mp4a / 0x6134706D), 48000 Hz, stereo, s16, 128 kb/s (default)
    Metadata:
      creation_time   : 2021-02-13T11:20:22.000000Z
      handler_name    : SoundHandle
      vendor_id       : [0][0][0][0]
      encoder         : Lavc59.12.100 libfdk_aac
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "sample value too large"', src/api/lookahead.rs:154:47
stack backtrace:
   0:     0x5595ac3d7aec - <unknown>
   1:     0x5595ac43430c - <unknown>
   2:     0x5595ac3c8b75 - <unknown>
   3:     0x5595ac3db050 - <unknown>
   4:     0x5595ac3dac07 - <unknown>
   5:     0x5595ac3db844 - <unknown>
   6:     0x5595ac3db320 - <unknown>
   7:     0x5595ac3d7fb4 - <unknown>
   8:     0x5595ac3db289 - <unknown>
   9:     0x5595aa7f2311 - <unknown>
  10:     0x5595aa7f2403 - <unknown>
  11:     0x5595ac2fbc97 - <unknown>
  12:     0x5595ac4ede7b - <unknown>
  13:     0x5595ac4fa290 - <unknown>
  14:     0x5595aa7eedc1 - <unknown>
  15:     0x5595ac395753 - <unknown>
  16:     0x5595ac398261 - <unknown>
  17:     0x5595ac52d3eb - <unknown>
  18:     0x5595ac3e7eb3 - <unknown>
  19:     0x7fc5d4ff9450 - start_thread
                               at ./nptl/./nptl/pthread_create.c:473:8
  20:     0x7fc5d4306d53 - clone
  21:                0x0 - <unknown>
fatal runtime error: failed to initiate panic, error 5
Abortado (`core' generado)
```
<Details>
CPU AMD Ryzen 9 5900X
+21Gb of free RAM

Video `mediainfo`

```
mediainfo 20210213_121844.mp4 
General
Complete name                            : 20210213_121844.mp4
Format                                   : MPEG-4
Format profile                           : Base Media / Version 2
Codec ID                                 : mp42 (isom/mp42)
File size                                : 624 MiB
Duration                                 : 1 min 37 s
Overall bit rate                         : 53.9 Mb/s
Encoded date                             : UTC 2021-02-13 11:20:22
Tagged date                              : UTC 2021-02-13 11:20:22
com.android.version                      : 11

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L5.1@Main
HDR format                               : SMPTE ST 2094 App 4, Version 1, HDR10+ Profile B compatible
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 1 min 37 s
Source duration                          : 1 min 37 s
Bit rate                                 : 53.7 Mb/s
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Display aspect ratio                     : 16:9
Rotation                                 : 90°
Frame rate mode                          : Variable
Frame rate                               : 29.970 (29970/1000) FPS
Minimum frame rate                       : 10.000 FPS
Maximum frame rate                       : 30.040 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.216
Stream size                              : 621 MiB (100%)
Source stream size                       : 621 MiB (100%)
Title                                    : VideoHandle
Language                                 : English
Encoded date                             : UTC 2021-02-13 11:20:22
Tagged date                              : UTC 2021-02-13 11:20:22
Color range                              : Limited
Color primaries                          : BT.2020
Transfer characteristics                 : PQ
Matrix coefficients                      : BT.2020 non-constant
Mastering display color primaries        : Display P3
Mastering display luminance              : min: 0.0050 cd/m2, max: 1000 cd/m2
mdhd_Duration                            : 97123
Codec configuration box                  : hvcC

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : mp4a-40-2
Duration                                 : 1 min 37 s
Bit rate mode                            : Constant
Bit rate                                 : 256 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 46.875 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 2.96 MiB (0%)
Title                                    : SoundHandle
Language                                 : English
Encoded date                             : UTC 2021-02-13 11:20:22
Tagged date                              : UTC 2021-02-13 11:20:22
```
</Details>

**Comment by barrbrain** [comment]
It looks like this should be resolved in v0.5.0 by #2794. (Also in v0.5.0-beta.2)

**Comment by rubdottocom** [comment]
I followed this tutorial to configure rav1e: https://askubuntu.com/a/1190778

So I did something like:

```
sudo apt-get install nasm build-essential libssl-dev && 
mkdir -pv $HOME/{bin,ffmpeg_sources,ffmpeg_build} && 
cd $HOME/ffmpeg_sources && 
wget https://github.com/xiph/rav1e/archive/refs/tags/v0.5.0.tar.gz && 
tar xvf v0.5.0.tar.gz && cd rav1e-0.5.0 && 
cargo build --release && 
find target -name rav1e -exec install -m 755 {} $HOME/bin \; && 
strip ~/bin/rav1e && \
cd $HOME/ffmpeg_sources && rm -rfv rav1e-0.5.0
```

I don't know why `rav1e --version` outputs 0.5.0beta

Should I pivot to a weekly pre-release or go back to beta2 release?

**Comment by barrbrain** [comment]
> I don't know why rav1e --version outputs 0.5.0beta

To check the location of the rav1e binary, run: `which rav1e`

It seems like you have another version of rav1e installed that is being picked up by ffmpeg.
To check the library path, run: `pkg-config --variable=libdir rav1e`

**Comment by rubdottocom** [comment]
I re-installed rav1 so I get 0.5.0 from `rav1e --version` .

Error persists on some videos, I'm finding new ones.

I found that lowering quality from to `-speed 4` to `-speed 8` encode the video, but I'm not confortable with this quality decrease, anyway I admit that I'm not sure to notice the difference, but video size is reduced to a 15-20% of an HEVC, I think is too much.

@barrbrain I don't know what to do with your suggestion, `which rav1e` outputs `/home/my_user/bin/rav1e` and `pkg-config --variable=libdir rav1e` outputs:

```
Package rav1e was not found in the pkg-config search path.
Perhaps you should add the directory containing `rav1e.pc'
to the PKG_CONFIG_PATH environment variable
No package 'rav1e' found
```

I don't know what to do after this message :(

Thank you!

**Comment by barrbrain** [comment]
> ```
> Package rav1e was not found in the pkg-config search path.
> ```

I think your ffmpeg binary is either a static build that includes librav1e `v0.5.0-beta` or it links from a non-standard location.
In the second case, we can check where it is finding librav1e:
```
ldd `which ffmpeg` | grep rav1e
```
If your ffmpeg binary is static, you will get an error like:
```
        not a dynamic executable
```

**Comment by rubdottocom** [comment]
```
ldd `which ffmpeg` | grep rav1e
```
No results

```
ldd `which ffmpeg`
```

```
	linux-vdso.so.1 (0x00007fffebdea000)
	libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f35e4add000)
	libxcb-shm.so.0 => /lib/x86_64-linux-gnu/libxcb-shm.so.0 (0x00007f35e4ad8000)
	libxcb-shape.so.0 => /lib/x86_64-linux-gnu/libxcb-shape.so.0 (0x00007f35e4ad3000)
	libxcb-xfixes.so.0 => /lib/x86_64-linux-gnu/libxcb-xfixes.so.0 (0x00007f35e4ac9000)
	libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007f35e49ce000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f35e4880000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f35e485c000)
	libSDL2-2.0.so.0 => /lib/x86_64-linux-gnu/libSDL2-2.0.so.0 (0x00007f35e46cc000)
	libsndio.so.7.0 => /lib/x86_64-linux-gnu/libsndio.so.7.0 (0x00007f35e46bb000)
	libXv.so.1 => /lib/x86_64-linux-gnu/libXv.so.1 (0x00007f35e44b6000)
	libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f35e44a1000)
	libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f35e4363000)
	libass.so.9 => /lib/x86_64-linux-gnu/libass.so.9 (0x00007f35e432c000)
	libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f35e4269000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f35e424d000)
	libva.so.2 => /lib/x86_64-linux-gnu/libva.so.2 (0x00007f35e4220000)
	libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f35e4023000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f35e401c000)
	libmp3lame.so.0 => /lib/x86_64-linux-gnu/libmp3lame.so.0 (0x00007f35e3fa2000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f35e3f87000)
	libvorbis.so.0 => /lib/x86_64-linux-gnu/libvorbis.so.0 (0x00007f35e3f59000)
	libvorbisenc.so.2 => /lib/x86_64-linux-gnu/libvorbisenc.so.2 (0x00007f35e3eae000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f35e3c95000)
	libmvec.so.1 => /lib/x86_64-linux-gnu/libmvec.so.1 (0x00007f35e3c69000)
	libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f35e3c5a000)
	libva-drm.so.2 => /lib/x86_64-linux-gnu/libva-drm.so.2 (0x00007f35e3c55000)
	libva-x11.so.2 => /lib/x86_64-linux-gnu/libva-x11.so.2 (0x00007f35e3c4d000)
	libvdpau.so.1 => /lib/x86_64-linux-gnu/libvdpau.so.1 (0x00007f35e3c47000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f35e3a5b000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f35e925b000)
	libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f35e3a55000)
	libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f35e3a4b000)
	libpulse.so.0 => /lib/x86_64-linux-gnu/libpulse.so.0 (0x00007f35e39f6000)
	libXcursor.so.1 => /lib/x86_64-linux-gnu/libXcursor.so.1 (0x00007f35e39ea000)
	libXinerama.so.1 => /lib/x86_64-linux-gnu/libXinerama.so.1 (0x00007f35e39e5000)
	libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007f35e39d3000)
	libXrandr.so.2 => /lib/x86_64-linux-gnu/libXrandr.so.2 (0x00007f35e39c4000)
	libXss.so.1 => /lib/x86_64-linux-gnu/libXss.so.1 (0x00007f35e39bf000)
	libXxf86vm.so.1 => /lib/x86_64-linux-gnu/libXxf86vm.so.1 (0x00007f35e39b8000)
	libdrm.so.2 => /lib/x86_64-linux-gnu/libdrm.so.2 (0x00007f35e39a4000)
	libgbm.so.1 => /lib/x86_64-linux-gnu/libgbm.so.1 (0x00007f35e3994000)
	libwayland-egl.so.1 => /lib/x86_64-linux-gnu/libwayland-egl.so.1 (0x00007f35e398f000)
	libwayland-client.so.0 => /lib/x86_64-linux-gnu/libwayland-client.so.0 (0x00007f35e397c000)
	libwayland-cursor.so.0 => /lib/x86_64-linux-gnu/libwayland-cursor.so.0 (0x00007f35e3971000)
	libxkbcommon.so.0 => /lib/x86_64-linux-gnu/libxkbcommon.so.0 (0x00007f35e392e000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f35e3923000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f35e390b000)
	libfribidi.so.0 => /lib/x86_64-linux-gnu/libfribidi.so.0 (0x00007f35e38ed000)
	libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f35e38a5000)
	libharfbuzz.so.0 => /lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f35e37bd000)
	libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f35e3782000)
	libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f35e3774000)
	libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f35e363b000)
	libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f35e3617000)
	libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f35e3495000)
	libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f35e347f000)
	libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007f35e3439000)
	libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007f35e33f1000)
	libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f35e336e000)
	libogg.so.0 => /lib/x86_64-linux-gnu/libogg.so.0 (0x00007f35e335f000)
	libXfixes.so.3 => /lib/x86_64-linux-gnu/libXfixes.so.3 (0x00007f35e3357000)
	libpulsecommon-14.2.so => /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-14.2.so (0x00007f35e32d7000)
	libdbus-1.so.3 => /lib/x86_64-linux-gnu/libdbus-1.so.3 (0x00007f35e3285000)
	libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f35e3278000)
	libwayland-server.so.0 => /lib/x86_64-linux-gnu/libwayland-server.so.0 (0x00007f35e3260000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f35e3231000)
	libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f35e3225000)
	libmd.so.0 => /lib/x86_64-linux-gnu/libmd.so.0 (0x00007f35e3218000)
	libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f35e320f000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f35e30d7000)
	libgraphite2.so.3 => /lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f35e30aa000)
	libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f35e3087000)
	libsystemd.so.0 => /lib/x86_64-linux-gnu/libsystemd.so.0 (0x00007f35e2fd1000)
	libwrap.so.0 => /lib/x86_64-linux-gnu/libwrap.so.0 (0x00007f35e2fc5000)
	libsndfile.so.1 => /lib/x86_64-linux-gnu/libsndfile.so.1 (0x00007f35e2f42000)
	libasyncns.so.0 => /lib/x86_64-linux-gnu/libasyncns.so.0 (0x00007f35e2d3c000)
	libapparmor.so.1 => /lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007f35e2d27000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f35e2cb1000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f35e2c86000)
	libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f35e2bb7000)
	liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f35e2b97000)
	libcap.so.2 => /lib/x86_64-linux-gnu/libcap.so.2 (0x00007f35e2b8c000)
	libgcrypt.so.20 => /lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f35e2a69000)
	libnsl.so.2 => /lib/x86_64-linux-gnu/libnsl.so.2 (0x00007f35e2a4e000)
	libFLAC.so.8 => /lib/x86_64-linux-gnu/libFLAC.so.8 (0x00007f35e2a0f000)
	libopus.so.0 => /lib/x86_64-linux-gnu/libopus.so.0 (0x00007f35e29af000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f35e2994000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f35e296c000)
	libtirpc.so.3 => /lib/x86_64-linux-gnu/libtirpc.so.3 (0x00007f35e293d000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f35e28e9000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f35e280f000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f35e27df000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f35e27d8000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f35e27c9000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f35e27c2000)
```

**Comment by shssoichiro** [comment]
Given that the bug that was originally posted seems to be fixed, I'm going to close this issue.

If you still need help getting the latest version of rav1e to compile, please stop by our IRC channel #daala on [Libera.Chat](https://libera.chat/). You can also use a [web client](https://web.libera.chat/?channel=#daala) to join with a web browser.
